/** biome-ignore-all lint/security/noSecrets: false positive */
export interface ResourceItem {
  title: string
  url: string
  favicon: string
  tags: string[]
  inverted?: boolean
}

export interface ResourceCategory {
  items: ResourceItem[]
}

export interface ResourceGroup {
  categories: Record<string, ResourceCategory>
}

export const RESOURCES: Record<string, ResourceGroup> = {
  development: {
    categories: {
      inspiration: {
        items: [
          {
            title: 'Recent Designs',
            url: 'https://recent.design',
            favicon: '/favicons/recent-designs.webp',
            tags: ['Animated', 'Motion', 'Unique', 'Experience', 'Interactive'],
          },
          {
            title: 'Toolfolio',
            url: 'https://toolfolio.io',
            favicon: '/favicons/toolfolio.webp',
            tags: ['Search', 'Up to date', 'Online', 'Tools', 'Startups'],
          },
          {
            title: 'UI Dux',
            url: 'https://www.uidux.com/industry/landing-page.html',
            favicon: '/favicons/ui-dux.webp',
            tags: ['Landing pages', 'Marketing', 'Sections', 'Topics', 'Web design'],
          },
          {
            title: 'Lander Website',
            url: 'https://blocks.lander.studio/?category=website',
            favicon: '/favicons/lander-website.webp',
            tags: ['Web design', 'Sections', 'Mobile apps', 'Illustrations'],
          },
          {
            title: 'Landingfolio',
            url: 'https://www.landingfolio.com/inspiration/landing-page',
            favicon: '/favicons/landingfolio.webp',
            tags: ['Web design', 'Full page', 'By industry'],
          },
          {
            title: 'Siteinspire',
            url: 'https://www.siteinspire.com/websites',
            favicon: '/favicons/siteinspire.webp',
            tags: ['Web design', 'Hero sections', 'By style', 'Modern'],
          },
          {
            title: 'Oxbow UI',
            url: 'https://oxbowui.com',
            favicon: '/favicons/oxbow-ui.webp',
            tags: [
              'Blocks',
              'Clean',
              'Modern',
              'Minimalistic',
              'Marketing',
              'Dashboard',
              'E-commerce',
            ],
          },
          {
            title: 'Refero',
            url: 'https://refero.design',
            favicon: '/favicons/refero.webp',
            tags: ['UI', 'Dashboard', 'UX patterns', 'Flows', 'Web design', 'Mobile app'],
          },
          {
            title: 'Minimal Gallery',
            url: 'https://minimal.gallery/websites',
            favicon: '/favicons/minimal-gallery.webp',
            tags: ['Minimalistic', 'Clean', 'Modern', 'Web design', 'Interactive'],
          },
          {
            title: 'Land Book',
            url: 'https://land-book.com',
            favicon: '/favicons/land-book.webp',
            tags: [
              'Web design',
              'Sections',
              'Mobile apps',
              'Motion',
              'Open graph',
              'Company websites',
            ],
          },
          {
            title: 'Craftwork',
            url: 'https://craftwork.design/curated/websites',
            favicon: '/favicons/craftwork.webp',
            tags: ['Web design', 'Hero sections', 'Unique', 'Marketing'],
          },
          {
            title: 'Maxi Best Of',
            url: 'https://maxibestof.one',
            favicon: '/favicons/maxi-best-of.webp',
            tags: ['Web design', 'Unique', 'Modern design', 'Niche'],
          },
          {
            title: 'Keitoto Studio',
            url: 'https://keitotostudio.dribbble.com',
            favicon: '/favicons/keitoto-studio.webp',
            tags: ['UI', 'Dashboard', 'Mobile app', 'UX', 'Components', 'Sections'],
          },
          {
            title: 'FillloDesign',
            url: 'https://dribbble.com/filllodesign',
            favicon: '/favicons/filllodesign.webp',
            tags: ['UI', 'Dashboard', 'Mobile app', 'UX', 'Components', 'Sections'],
          },
          {
            title: 'Tailark Pro',
            url: 'https://pro.tailark.com',
            favicon: '/favicons/tailark-pro.webp',
            tags: ['UI', 'Components', 'Modern', 'Minimalistic', 'Sections'],
          },
          {
            title: 'Supahero',
            url: 'https://supahero.io',
            favicon: '/favicons/supahero.webp',
            tags: ['Web design', 'Unique', 'Marketing', 'Hero sections'],
          },
          {
            title: 'Viewport UI',
            url: 'https://viewport-ui.design',
            favicon: '/favicons/viewport-ui.webp',
            tags: ['Web design', 'Mobile app', 'Motion', 'UX', 'Interactions'],
            inverted: true,
          },
          {
            title: 'A/B Test',
            url: 'https://abtest.design/',
            favicon: '/favicons/ab-test.webp',
            tags: ['Collection', 'Mobile app', 'Marketing', 'By category'],
            inverted: true,
          },
          {
            title: 'Loadmore',
            url: 'https://loadmo.re',
            favicon: '/favicons/loadmore.webp',
            tags: [
              'Web design',
              'Mobile app',
              'Animated',
              'Unique',
              'Design styles',
              'Alternative',
            ],
          },
          {
            title: 'Framer Community Gallery',
            url: 'https://www.framer.com/community/gallery',
            favicon: '/favicons/framer-community-gallery.webp',
            tags: ['Web design', 'Unique', 'Portfolios', 'Landing page', 'Agencies'],
          },
          {
            title: 'See Saw',
            url: 'https://www.seesaw.website',
            favicon: '/favicons/see-saw.webp',
            tags: ['Web design', 'Unique', 'Animated', 'Experiencial'],
          },
          {
            title: 'Design Spells',
            url: 'https://designspells.com',
            favicon: '/favicons/design-spells.webp',
            tags: ['Web design', 'Mobile apps', 'Motion', 'UX', 'Micro-interactions'],
          },
        ],
      },
      componentSets: {
        items: [
          {
            title: 'UI Verse',
            tags: ['Community', 'Buttons', 'Inputs', 'Loaders', 'Backgrounds', 'Patterns'],
            url: 'https://uiverse.io',
            favicon: '/favicons/ui-verse.webp',
          },
          {
            title: 'ReUI',
            url: 'https://reui.io/components',
            favicon: '/favicons/reui.webp',
            tags: ['Modern', 'Clean', 'Interactive', 'Web design'],
          },
          {
            title: 'Coss UI',
            url: 'https://coss.com/ui',
            favicon: '/favicons/coss-ui.webp',
            tags: ['Modern', 'Clean', 'Interactive', 'Web design'],
          },
          {
            title: '21st',
            url: 'https://21st.dev',
            favicon: '/favicons/21st.webp',
            tags: ['Community', 'Modern', 'Animated', 'Interactive', 'Web design'],
          },

          {
            title: 'UntitledUI',
            tags: ['React Aria', 'Design system', 'Easy to use', 'Components'],
            url: 'https://www.untitledui.com/react',
            favicon: '/favicons/untitledui.webp',
          },
          {
            title: 'Align UI',
            url: 'https://www.alignui.com',
            favicon: '/favicons/align-ui.webp',
            tags: ['Composable', 'Modern', 'Design system', 'Easy to use'],
          },
          {
            title: 'Preline',
            tags: ['Modern', 'Clean', 'Plain HTML', 'JavaScript', 'Blocks'],
            url: 'https://preline.co',
            favicon: '/favicons/preline.webp',
          },
          {
            title: 'Shadcn IO',
            url: 'https://www.shadcn.io/components',
            favicon: '/favicons/shadcn-io.webp',
            tags: ['Modern', 'Clean', 'Interactive', 'Composable'],
          },
          {
            title: 'Board UI',
            url: 'https://www.boardui.com/components',
            favicon: '/favicons/board-ui.webp',
            tags: ['Modern', 'Clean', 'Blocks', 'Dashboard', 'Design system', 'Components'],
          },
          {
            title: 'Free Frontend',
            tags: ['Demo and code', 'CSS', 'HTML', 'JavaScript'],
            url: 'https://freefrontend.com',
            favicon: '/favicons/free-frontend.webp',
          },
          {
            title: 'Shadcn Blocks',
            url: 'https://www.shadcnblocks.com/blocks',
            favicon: '/favicons/shadcn-blocks.webp',
            tags: ['By category', 'Modern', 'Minimalistic'],
          },
          {
            title: 'TermCN',
            url: 'https://www.termcn.dev/',
            favicon: '/favicons/termcn.webp',
            tags: ['Interactive', 'TUI', 'CLI', 'Terminal', 'Modern'],
          },
          {
            title: 'Devl',
            url: 'https://www.devl.dev/',
            favicon: '/favicons/devl.webp',
            tags: ['Blocks', 'Modern', 'Minimalistic', 'Dashboard', 'Marketing'],
          },
          {
            title: 'Square UI',
            url: 'https://square.lndevui.com/',
            favicon: '/favicons/square-ui.webp',
            tags: ['Blocks', 'Layouts', 'Templates', 'Dashboard', 'Web'],
          },
          {
            title: 'Beautiful UI',
            tags: ['Animated', 'AI', 'Agents', 'Chatbot'],
            url: 'https://www.beautifului.dev',
            favicon: '/favicons/beautiful-ui.webp',
          },
          {
            title: 'BeUI',
            tags: ['Animated', 'AI', 'Agents', 'Chatbot'],
            url: 'https://beui.dev/components/motion',
            favicon: '/favicons/beui.webp',
          },
        ],
      },
      fancyComponents: {
        items: [
          {
            title: 'React Bits',
            tags: ['Text', 'Backgrounds', 'Components', 'Animated', 'Studio', 'Lab'],
            url: 'https://reactbits.dev',
            favicon: '/favicons/react-bits.webp',
          },
          {
            title: 'Border beam',
            tags: ['Single', 'React', 'SwiftUI', 'React Native'],
            url: 'https://beam.jakubantalik.com/pulse',
            favicon: '/favicons/border-beam.webp',
          },
          {
            title: 'Gooey',
            url: 'https://gooey.jakubantalik.com',
            favicon: '/favicons/gooey.webp',
            tags: ['Liquid glass', 'Interactive', 'Single'],
          },
          {
            title: 'Three UI',
            tags: ['3D', 'Interactive', 'Three.js', 'Blocks', 'Backgrounds', 'Text', 'Buttons'],
            url: 'https://threeui.com/browse',
            favicon: '/favicons/three-ui.webp',
          },
          {
            title: 'OriginKit',
            url: 'https://www.originkit.dev/',
            favicon: '/favicons/originkit.webp',
            tags: ['Sections', 'Backgrounds', 'Interactive', 'Templates', 'Gallery'],
          },
          {
            title: 'UseAnimations Icons',
            tags: ['Animated', 'Interactive', 'Online', 'Motion'],
            url: 'https://react.useanimations.com',
            favicon: '/favicons/useanimations-icons.webp',
          },
          {
            title: 'Spoiled',
            tags: ['Confidential info', 'Animated', 'Single'],
            url: 'https://spoiled.vercel.app',
            favicon: '/favicons/spoiled.webp',
          },
          {
            title: 'Generative Loaders',
            url: 'https://generativeloaders.com',
            favicon: '/favicons/generative-loaders.webp',
            tags: ['Streaming', 'Skeleton', 'Placeholders', 'Motion', 'Animated'],
          },

          {
            title: 'Vengence UI',
            tags: ['Next.js', 'Hover effects', 'Futuristic', 'Dark'],
            url: 'https://www.vengenceui.com',
            favicon: '/favicons/vengence-ui.webp',
          },
          {
            title: 'Fancy Components',
            tags: ['Fun and weird', 'Micro-interactions', 'UI'],
            url: 'https://fancycomponents.dev',
            favicon: '/favicons/fancy-components.webp',
          },
          {
            title: 'Rare UI',
            url: 'https://www.rareui.com/components',
            favicon: '/favicons/rare-ui.webp',
            tags: ['Motion', 'UI', 'Animations', 'Unique', 'Smooth'],
          },
          {
            title: 'Interior UI',
            url: 'https://www.interior.dev',
            favicon: '/favicons/interior-ui.webp',
            tags: ['Micro-interactions', 'Modern', 'UX', 'Motion'],
          },
          {
            title: 'Fluid Functionalism',
            url: 'https://www.fluidfunctionalism.com/docs',
            favicon: '/favicons/fluid-functionalism.webp',
            tags: ['Micro-interactions', 'Modern', 'UX', 'Motion'],
          },
          {
            title: 'Amicro',
            url: 'https://amicro.vercel.app/cards',
            favicon: '/favicons/amicro.webp',
            tags: ['Motion', 'Buttons', 'Loaders', 'Cards', 'Gallery'],
          },
          {
            title: 'BadtzUI Particles',
            tags: ['Backgrounds', 'Stars', 'Snow', 'Interactive'],
            url: 'https://www.badtz-ui.com/docs/components/particles',
            favicon: '/favicons/badtzui-particles.webp',
          },
          {
            title: 'Animate UI Cursor',
            tags: ['Figma-like', 'Cursor', 'Following text'],
            url: 'https://animate-ui.com/docs/components/animate/cursor',
            favicon: '/favicons/animate-ui-cursor.webp',
          },
          {
            title: 'Motion Primitives',
            tags: ['Smooth', 'Micro-interactions', 'Clean'],
            url: 'https://motion-primitives.com/docs',
            favicon: '/favicons/motion-primitives.webp',
          },
          {
            title: 'Aceternity UI',
            tags: [
              'Blocks',
              'Illustrations',
              'Backgrounds',
              'Effects',
              'Scroll',
              'Text',
              'Overlay',
            ],
            url: 'https://ui.aceternity.com',
            favicon: '/favicons/aceternity-ui.webp',
          },
          {
            title: 'Cult UI',
            tags: [
              'Sections',
              'Widgets',
              'Cards',
              'Buttons',
              'Textures',
              'Visual sistems',
              'Media',
              'Text',
            ],
            url: 'https://cult-ui.com',
            favicon: '/favicons/cult-ui.webp',
          },
          {
            title: 'Lunar UI',
            tags: ['Features section', 'Text', 'Scroll', 'Navigation', 'Buttons', 'Patterns'],
            url: 'https://lunarui.dev',
            favicon: '/favicons/lunar-ui.webp',
          },
          {
            title: 'Thinking Orbs',
            url: 'https://orbs.jakubantalik.com',
            favicon: '/favicons/thinking-orbs.webp',
            tags: ['Chatbot', 'Agents', 'UX', 'Motion'],
          },
          {
            title: 'Number Flow',
            url: 'https://number-flow.barvian.me',
            favicon: '/favicons/number-flow.webp',
            tags: ['Number', 'Single', 'Animated', 'Motion', 'Smooth'],
          },
          {
            title: 'Torph',
            url: 'https://torph.lochie.me',
            favicon: '/favicons/torph.webp',
            tags: ['Text', 'Morphing', 'Single', 'Motion', 'Animated'],
          },
          {
            title: 'Calligraph',
            url: 'https://calligraph.raphaelsalaja.com/',
            favicon: '/favicons/calligraph.webp',
            tags: ['Text', 'Morphing', 'Single', 'Motion', 'Animated'],
          },
        ],
      },
      singleComponents: {
        items: [
          {
            title: 'Facehash',
            tags: ['Minimalistic', 'Avatars', 'Customizable', 'Generator', 'Zero dependencies'],
            url: 'https://www.facehash.dev',
            favicon: '/favicons/facehash.webp',
          },
          {
            title: 'Outpace Avatars',
            tags: ['Generator', 'Avatars', 'Minimalistic', 'Gradient'],
            url: 'https://avatars.outpacestudios.com',
            favicon: '/favicons/outpace-avatars.webp',
          },
          {
            title: 'Sound effect',
            url: 'https://audio.raphaelsalaja.com/',
            favicon: '/favicons/sound-effect.webp',
            tags: ['Audio', 'Generator', 'SFX', 'Filters', 'Effects'],
          },
          {
            title: 'Cuelume',
            url: 'https://cuelume.dev/',
            favicon: '/favicons/cuelume.webp',
            tags: ['Audio', 'Generator', 'SFX', 'Collection'],
          },
          {
            title: 'Web Haptics',
            url: 'https://haptics.lochie.me/',
            favicon: '/favicons/web-haptics.webp',
            tags: ['Feedback', 'Sounds', 'SFX'],
          },
          {
            title: 'MapCN',
            url: 'https://www.mapcn.dev/',
            favicon: '/favicons/mapcn.webp',
            tags: ['Maps', 'Interactive', 'Globe', 'Blocks'],
          },
          {
            title: 'PDF Slick',
            url: 'https://pdfslick.dev/',
            favicon: '/favicons/pdf-slick.webp',
            tags: ['Viewer', 'Interactive', 'Documents'],
          },
          {
            title: 'Cookie Banner',
            tags: ['Next.js', 'JavaScript', 'Client and SSR', 'Themable'],
            url: 'https://c15t.com',
            favicon: '/favicons/cookie-banner.webp',
          },
          {
            title: 'Morphicons',
            url: 'https://www.morphicons.com',
            favicon: '/favicons/morphicons.webp',
            tags: ['Animated', 'Icons', 'Lucide', 'Tabler', 'Hero', 'Spring'],
          },
          {
            title: 'Shader Tool',
            tags: ['Gradient', 'Backgrounds'],
            url: 'https://shader-tool.vercel.app',
            favicon: '/favicons/shader-tool.webp',
            inverted: true,
          },
          {
            title: 'Emoji picker',
            tags: ['Unstyled', 'Composable'],
            url: 'https://frimousse.liveblocks.io',
            favicon: '/favicons/emoji-picker.webp',
          },
          {
            title: 'Boneyard',
            url: 'https://boneyard.vercel.app/overview',
            favicon: '/favicons/boneyard.webp',
            tags: ['Skeleton', 'Generator', 'Responsive'],
          },
          {
            title: 'Stepperize',
            tags: ['Navigation', 'Progress bar', 'Themable'],
            url: 'https://stepperize.vercel.app/docs/latest',
            favicon: '/favicons/stepperize.webp',
          },
          {
            title: 'Responsive pagination',
            tags: ['Themable', 'Interactive'],
            url: 'https://react-responsive-pagination.elantha.com',
            favicon: '/favicons/responsive-pagination.webp',
          },
          {
            title: '3D Book generator',
            tags: ['CSS only', 'Customizable', 'Interactive'],
            url: 'https://scastiel.dev/3dbook',
            favicon: '/favicons/3d-book-generator.webp',
          },
          {
            title: 'Photoswipe',
            tags: ['Zoom image', 'Gallery'],
            url: 'https://photoswipe.com',
            favicon: '/favicons/photoswipe.webp',
          },
          {
            title: 'Theme Toggle',
            tags: ['View transitions', 'Masking', 'Animated'],
            url: 'https://theme-toggle.rdsx.dev',
            favicon: '/favicons/theme-toggle.webp',
          },
          {
            title: 'Driver.js',
            tags: ['Onboarding', 'Tour', 'Customizable'],
            url: 'https://driverjs.com',
            favicon: '/favicons/driverjs.webp',
          },
          {
            title: 'Model viewer',
            tags: ['3D', 'Online', 'AR'],
            url: 'https://modelviewer.dev',
            favicon: '/favicons/model-viewer.webp',
          },
          {
            title: 'SoundCn',
            tags: ['Music', 'Sounds', 'Feedback'],
            url: 'https://www.soundcn.xyz',
            favicon: '/favicons/soundcn.webp',
          },
          {
            title: 'Blendy',
            tags: ['Element transitions', 'Framework agnostic', 'Morphing'],
            url: 'https://blendy.tahazsh.com',
            favicon: '/favicons/blendy.webp',
          },
          {
            title: 'BProgress',
            tags: ['Progress bar', 'Loading bar', 'Next.js'],
            url: 'https://bprogress.vercel.app/docs',
            favicon: '/favicons/bprogress.webp',
          },
        ],
      },
      charts: {
        items: [
          {
            title: 'Evil charts',
            tags: ['Data visualization', 'Themable'],
            url: 'https://evilcharts.com/docs',
            favicon: '/favicons/evil-charts.webp',
          },
          {
            title: 'Mermaid',
            tags: ['Graphs', 'Diagrams', 'Markdown'],
            url: 'https://mermaid.ai/open-source/intro',
            favicon: '/favicons/mermaid.webp',
          },
          {
            title: 'TanStack Charts',
            tags: ['Data visualization', 'Advanced'],
            url: 'https://tanstack.com/charts/catalog',
            favicon: '/favicons/tanstack-charts.webp',
          },
          {
            title: 'Rosen Charts',
            tags: ['Data visualization', 'Customizable'],
            url: 'https://rosencharts.com',
            favicon: '/favicons/rosen-charts.webp',
          },
          {
            title: 'Lightweight charts',
            tags: ['Financial charts', 'Data visualization', 'Zoomable'],
            url: 'https://tradingview.github.io/lightweight-charts',
            favicon: '/favicons/lightweight-charts.webp',
          },

          {
            title: 'React Flow',
            tags: ['Diagrams', 'Editor', 'Workflow', 'Nodes', 'Graph'],
            url: 'https://reactflow.dev',
            favicon: '/favicons/react-flow.webp',
          },
          {
            title: 'Dither Kit',
            tags: ['Styled', 'Gradient', 'Animated', 'Interactive'],
            url: 'https://www.tripwire.sh/dither-kit',
            favicon: '/favicons/dither-kit.webp',
          },
        ],
      },
      hooksAndUtils: {
        items: [
          {
            title: 'UseToolKit',
            tags: ['Lodash alternative', 'TypeScript', 'Utility'],
            url: 'https://es-toolkit.dev/intro.html',
            favicon: '/favicons/usetoolkit.webp',
          },
          {
            title: 'React Use',
            tags: ['Sensors', 'UI', 'Animated', 'Side effects', 'Lifecycles', 'State'],
            url: 'https://github.com/streamich/react-use',
            favicon: '/favicons/react-use.webp',
          },
          {
            title: 'UseHooks TS',
            tags: ['Common use', 'DRY', 'Simple'],
            url: 'https://usehooks-ts.com/introduction',
            favicon: '/favicons/usehooks-ts.webp',
          },
          {
            title: 'Just',
            tags: ['Tiny', 'Zero dependency', 'Lodash alternative'],
            url: 'http://github.com/angus-c/just',
            favicon: '/favicons/just.webp',
          },
          {
            title: 'Foresight',
            tags: ['UX', 'Prefetching', 'Cursor intent', 'Scroll intent'],
            url: 'https://foresightjs.com',
            favicon: '/favicons/foresight.webp',
          },
          {
            title: 'Recent Designs Skills',
            url: 'https://recent.design/skills',
            favicon: '/favicons/recent-designs-skills.webp',
            tags: ['AI', 'Agents', 'UI skills'],
          },
          {
            title: 'Permix',
            tags: ['Permission handling', 'Framework agnostic', 'Client side', 'Server side'],
            url: 'https://permix.letstri.dev',
            favicon: '/favicons/permix.webp',
          },
          {
            title: 'Lorca',
            tags: ['Natural language processing', 'Spanish', 'Words', 'Syllables', 'Concordance'],
            url: 'https://github.com/dmarman/lorca',
            favicon: '/favicons/lorca.webp',
          },
          {
            title: 'Autoskills.sh',
            url: 'https://www.autoskills.sh',
            favicon: '/favicons/autoskillssh.webp',
            tags: ['AI', 'Agents', 'CLI', 'Open Source'],
          },
          {
            title: 'Nuclei',
            url: 'https://github.com/projectdiscovery/nuclei',
            favicon: '/favicons/nuclei.webp',
            tags: ['Security', 'Vulnerability', 'Scanning', 'CLI', 'Open Source'],
          },
          {
            title: 'Easing Dev',
            url: 'https://www.easing.dev',
            favicon: '/favicons/easing-dev.webp',
            tags: ['Cubic bezier', 'Motion', 'Showcase'],
          },
        ],
      },
      backgrounds: {
        items: [
          {
            title: 'Fluid Shader',
            tags: ['Shader', 'Online', 'Editor'],
            url: 'https://fluidshader.vercel.app',
            favicon: '/favicons/fluid-shader.webp',
          },
          {
            title: 'Gradient Animator',
            tags: ['CSS', 'Animation', 'Online'],
            url: 'https://gradient-animator.vercel.app',
            favicon: '/favicons/gradient-animator.webp',
          },
          {
            title: 'Photogradient',
            tags: ['Gradient', 'Mesh', 'Noisy'],
            url: 'https://photogradient.com',
            favicon: '/favicons/photogradient.webp',
          },
          {
            title: 'Easing gradients',
            tags: ['Gradient', 'Smooth', 'CSS'],
            url: 'https://larsenwork.com/easing-gradients/#editor',
            favicon: '/favicons/easing-gradients.webp',
          },
          {
            title: 'Shader Gradient',
            tags: ['Gradient', 'Animated', 'Motion'],
            url: 'https://www.shadergradient.co/customize',
            favicon: '/favicons/shader-gradient.webp',
          },
        ],
      },
    },
  },
  design: {
    categories: {
      general: {
        items: [
          {
            title: 'Freesets',
            tags: [
              'icons',
              'illustrations',
              'photos',
              'videos',
              'typography',
              '3d',
              'fonts',
              'colors',
              'backgrounds',
            ],
            url: 'https://freesets.vercel.app',
            favicon: '/favicons/freesets.webp',
            inverted: true,
          },
          {
            title: 'Tiny Helpers',
            url: 'https://tiny-helpers.dev',
            favicon: '/favicons/tiny-helpers.webp',
            tags: ['Tools', 'Helpers', 'Single Porpuse'],
          },
          {
            title: 'Pixel Buddha',
            tags: [
              'Mockups',
              'Fonts',
              'Image effects',
              'Text effects',
              'Textures',
              'Brushes',
              'Graphics',
            ],
            url: 'https://pixelbuddha.net',
            favicon: '/favicons/pixel-buddha.webp',
          },
          {
            title: 'Resource Boy',
            tags: ['3D', 'Fonts', 'Patterns', 'Brushes', 'Mockups', 'Textures'],
            url: 'https://resourceboy.com',
            favicon: '/favicons/resource-boy.webp',
          },
        ],
      },
      inspiration: {
        items: [
          {
            title: 'Recent Designs',
            url: 'https://recent.design',
            favicon: '/favicons/recent-designs.webp',
            tags: ['Motion', 'Posters', 'Effects', 'Styles', 'Unique', 'Open graphs', 'Apps'],
          },
          {
            title: 'Cosmos Graphic Design',
            url: 'https://www.cosmos.so/explore/graphic-design',
            favicon: '/favicons/cosmos-graphic-design.webp',
            tags: ['Posters', 'Social media', 'Design styles', 'Community'],
          },
        ],
      },
      iconsAndIllustrations: {
        items: [
          {
            title: '@andrsrxn/icons',
            tags: ['Duotone', 'Flags', 'SVG', 'RTL aware', 'Smooth', 'Clean'],
            url: 'https://github.com/andrsrxn/icons#readme',
            favicon: '/favicons/andrsrxnicons.webp',
          },
          {
            title: 'SVGL',
            url: 'https://svgl.app',
            favicon: '/favicons/svgl.webp',
            tags: ['Brands', 'Logos', 'Dark mode', 'Wordmarks', 'Symbols'],
          },
          {
            title: 'Reicon Icons',
            url: 'https://reicon.dev/icons',
            favicon: '/favicons/reicon-icons.webp',
            tags: ['Outline', 'Filled', 'Two-tone', 'Smooth', 'Customizable', 'Adaptable'],
          },
          {
            title: 'Hugeicons',
            url: 'https://hugeicons.com/icons',
            favicon: '/favicons/hugeicons.webp',
            tags: ['Outline', 'Filled', 'Two-tone', 'Smooth', 'Customizable', 'Adaptable'],
          },
          {
            title: 'Phosphor Icons',
            url: 'https://phosphoricons.com',
            favicon: '/favicons/phosphor-icons.webp',
            tags: ['Outline', 'Filled', 'Duotone', 'Logos', 'Bold', 'Thin'],
          },
          {
            title: 'Tabler Icons',
            url: 'https://tabler.io/icons',
            favicon: '/favicons/tabler-icons.webp',
            tags: ['Outline', 'Filled', 'Logos'],
          },
          {
            title: 'Isocons',
            url: 'https://www.isocons.app',
            favicon: '/favicons/isocons.webp',
            tags: ['Isometric', '3D', 'Filled', 'Outline', 'Rounded'],
          },
          {
            title: 'Lucide Icons Animated',
            url: 'https://icons.pqoqubbw.dev',
            favicon: '/favicons/lucide-icons-animated.webp',
            tags: ['Motion', 'TSX', 'Outline', 'Smooth'],
          },
          {
            title: 'The SVG',
            url: 'https://thesvg.org',
            favicon: '/favicons/the-svg.webp',
            tags: ['Logos', 'Brands', 'AWS', 'Google Cloud', 'Azure', 'Up to date', 'Dark mode'],
          },
          {
            title: 'Simple Icons',
            url: 'https://simpleicons.org',
            favicon: '/favicons/simple-icons.webp',
            tags: ['Logos', 'Brands', 'Monochrome'],
          },
          {
            title: 'Avatar Bot 2D',
            url: 'https://avatars.bible-strong.app',
            favicon: '/favicons/avatar-bot-2d.webp',
            tags: ['Animated', 'SVG', 'Mascot', 'Interactive'],
          },
          {
            title: 'Open Peeps',
            tags: ['Illustrations', 'People', 'Monochrome', 'Marketing', 'Comics'],
            url: 'https://www.openpeeps.com',
            favicon: '/favicons/open-peeps.webp',
          },
          {
            title: 'Koboyo Icons',
            tags: ['Illustrations', 'People', 'Monochrome', 'Objects', 'Scenes'],
            url: 'https://koboyo.com/icons',
            favicon: '/favicons/koboyo-icons.webp',
          },
          {
            title: 'Cool Shapes',
            tags: ['Gradient', 'PNG', 'SVG', 'Illustrations', 'Shape art', 'Noisy', 'Mesh'],
            url: 'https://coolshap.es',
            favicon: '/favicons/cool-shapes.webp',
          },
          {
            title: 'Thiings',
            tags: [
              '3D',
              'Illustrations',
              'AI generated',
              'Countries',
              'Animals',
              'Vehicles',
              'Technology',
            ],
            url: 'https://www.thiings.co/things',
            favicon: '/favicons/thiings.webp',
          },
          {
            title: 'Blobs SVG',
            tags: ['Animated', 'Illustrations', 'Abstract', 'GIF'],
            url: 'https://blobs.xom9ik.com/svg',
            favicon: '/favicons/blobs-svg.webp',
          },
          {
            title: 'Polyhaven',
            tags: ['3D', 'Textures', 'HDRi', 'Models', 'Blender'],
            url: 'https://www.polyhaven.com/all',
            favicon: '/favicons/polyhaven.webp',
          },
          {
            title: 'Heritage Type Vintage Illustrations',
            tags: [
              'Colored',
              'Monochrome',
              'Animals',
              'Objects',
              'Nature',
              'Fruits',
              'People',
              'Clothes',
            ],
            url: 'https://www.heritagetype.com/pages/free-vintage-illustrations',
            favicon: '/favicons/heritage-type-vintage-illustrations.webp',
          },
          {
            title: 'World in Dots',
            tags: ['Maps', 'Countries', 'Monochrome', 'PNG'],
            url: 'https://www.worldindots.com',
            favicon: '/favicons/world-in-dots.webp',
          },
        ],
      },
      branding: {
        items: [
          {
            title: 'The Brand Identity',
            url: 'https://the-brandidentity.com',
            favicon: '/favicons/the-brand-identity.webp',
            tags: ['Case studies', 'Blog'],
          },
          {
            title: 'Daily Branding',
            url: 'https://dailybranding.xyz/brands',
            favicon: '/favicons/daily-branding.webp',
            tags: ['Case studies', 'Blog'],
          },
          {
            title: 'Brand New',
            url: 'https://www.underconsideration.com/brandnew',
            favicon: '/favicons/brand-new.webp',
            tags: ['Case studies', 'Niche', 'Identity', 'Up to date'],
          },
          {
            title: 'Visual Journal',
            url: 'https://visualjournal.it',
            favicon: '/favicons/visual-journal.webp',
            tags: ['Modern', 'Minimalistic'],
          },
          {
            title: 'Brand Archive',
            url: 'https://brandarchive.xyz/identity/instagram-2026',
            favicon: '/favicons/brand-archive.webp',
            tags: ['Famous brands', 'Up to date'],
          },
          {
            title: 'Rebrand Gallery',
            url: 'https://www.rebrand.gallery',
            favicon: '/favicons/rebrand-gallery.webp',
            tags: ['Motion', 'Animated', 'Marketing', 'Reveal'],
          },
          {
            title: 'Startups Gallery',
            url: 'https://startups.gallery',
            favicon: '/favicons/startups-gallery.webp',
            tags: ['Startups', 'Modern'],
          },
          {
            title: 'Contra',
            url: 'https://contra.com/?view=projects',
            favicon: '/favicons/contra.webp',
            tags: ['Studios', 'Motion', 'Modern'],
          },
          {
            title: 'Namelix',
            url: 'https://namelix.com',
            favicon: '/favicons/namelix.webp',
            tags: ['Naming', 'Generator', 'AI'],
          },
          {
            title: 'Kittl',
            url: 'https://www.kittl.com',
            favicon: '/favicons/kittl.webp',
            tags: ['Branding visuals', 'Generator', 'Merchandising', 'Showcase'],
          },
        ],
      },
      logos: {
        items: [
          {
            title: 'Logggos',
            url: 'https://www.logggos.club',
            favicon: '/favicons/logggos.webp',
            tags: ['By industry', 'Modern', 'Typographic', 'By color'],
          },
          {
            title: 'Lander Logos',
            url: 'https://blocks.lander.studio/?category=logos',
            favicon: '/favicons/lander-logos.webp',
            tags: ['By letter', 'Abstract', 'Monochrome'],
          },
          {
            title: 'Logosystem',
            url: 'https://logosystem.co',
            favicon: '/favicons/logosystem.webp',
            tags: ['Banners', 'Symbols', 'Typographic'],
          },
          {
            title: 'Logo Book',
            url: 'https://logobook.com',
            favicon: '/favicons/logo-book.webp',
            tags: ['Abstract', 'Minimalistic', 'By category', 'Monochrome'],
          },
        ],
      },
      fonts: {
        items: [
          {
            title: '1001 Free Fonts',
            url: 'https://www.1001freefonts.com/es',
            favicon: '/favicons/1001-free-fonts.webp',
            tags: ['Discover', 'Sans', 'Serif', 'Script', 'Handwritten', 'By category'],
          },
          {
            title: '1001 Fonts',
            url: 'https://www.1001fonts.com',
            favicon: '/favicons/1001-fonts.webp',
            tags: ['Discover', 'Sans', 'Serif', 'Script', 'Handwritten', 'By category'],
          },
          {
            title: 'Calligrphr',
            url: 'https://www.calligraphr.com/es',
            favicon: '/favicons/calligrphr.webp',
            tags: ['Tool', 'Font generator', 'Custom fonts', 'Vectors'],
          },
          {
            title: 'Type Scale',
            url: 'https://typescale.com',
            favicon: '/favicons/type-scale.webp',
            tags: ['Tool', 'Type scale generator', 'Design system'],
          },
          {
            title: 'Fontspace',
            url: 'https://www.fontspace.com/new/fonts',
            favicon: '/favicons/fontspace.webp',
            tags: ['Discover', 'New fonts', 'Display'],
          },
          {
            title: 'Urban Fonts',
            url: 'https://urbanfonts.com/free-fonts',
            favicon: '/favicons/urban-fonts.webp',
            tags: ['Discover', 'Unique', 'Display'],
          },
          {
            title: 'Collletttivo',
            url: 'https://www.collletttivo.it/typefaces',
            favicon: '/favicons/collletttivo.webp',
            tags: ['Collection', 'Unique', 'Display', 'Modern'],
          },
          {
            title: 'Free Faces',
            url: 'https://www.freefaces.gallery',
            favicon: '/favicons/free-faces.webp',
            tags: ['Collection', 'Serif', 'Sans', 'Display', 'Modern'],
          },
          {
            title: 'Fontshare',
            url: 'https://www.fontshare.com',
            favicon: '/favicons/fontshare.webp',
            tags: ['Collection', 'Serif', 'Sans', 'Display', 'Modern'],
          },
          {
            title: 'Uncut Fonts',
            url: 'https://uncut.wtf',
            favicon: '/favicons/uncut-fonts.webp',
            tags: ['Collection', 'Serif', 'Sans', 'Display', 'Monospace'],
          },
          {
            title: 'Fontesk',
            url: 'https://fontesk.com/license/free-for-commercial-use',
            favicon: '/favicons/fontesk.webp',
            tags: ['Collection', 'Handwritten', 'Script', 'Community'],
          },
          {
            title: 'Pixel Buddha Fonts',
            url: 'https://pixelbuddha.net/fonts?type=freebie',
            favicon: '/favicons/pixel-buddha-fonts.webp',
            tags: ['Collection', 'Display', 'Script', 'Modern'],
          },
          {
            title: 'Fontmeme',
            url: 'https://fontmeme.com/es',
            favicon: '/favicons/fontmeme.webp',
            tags: ['Collection', 'Movies', 'Videogames', 'TV'],
          },
          {
            title: 'Sova Type Foundry',
            url: 'https://www.suvatypefoundry.ee',
            favicon: '/favicons/sova-type-foundry.webp',
            tags: ['Collection', 'Display', 'Unique', 'Script', 'Handwritten'],
          },
          {
            title: 'Velvetyne Type Foundry',
            url: 'https://velvetyne.fr',
            favicon: '/favicons/velvetyne-type-foundry.webp',
            tags: ['Collection', 'Display', 'Unique', 'Script', 'Geometric'],
          },
          {
            title: 'Use Modify',
            url: 'https://usemodify.com',
            favicon: '/favicons/use-modify.webp',
            tags: ['Collection', 'Sans', 'Serif', 'Display'],
          },
        ],
      },
      colors: {
        items: [
          {
            title: 'Tints',
            url: 'https://www.tints.dev',
            favicon: '/favicons/tints.webp',
            tags: ['Color generator', 'Shades', 'Lights', 'Palette'],
          },
          {
            title: 'Hihayk Scale',
            url: 'https://hihayk.github.io/scale',
            favicon: '/favicons/hihayk-scale.webp',
            tags: ['Color generator', 'Shades', 'Lights', 'Palette'],
          },
          {
            title: 'Coolors',
            url: 'https://coolors.co',
            favicon: '/favicons/coolors.webp',
            tags: ['Generator', 'Palette', 'Contrast checker'],
          },
          {
            title: 'Hex Color Pedia',
            url: 'https://hexcolorpedia.com',
            favicon: '/favicons/hex-color-pedia.webp',
            tags: ['Generator', 'Information', 'Converter', 'Combination'],
          },
          {
            title: 'Pantone to RAL',
            url: 'https://ursanpinturas.com/conversion-pantone-ral',
            favicon: '/favicons/pantone-to-ral.webp',
            tags: ['Converter', 'Color names', 'RAL', 'Pantone', 'Information'],
          },
          {
            title: 'Hex to Pantone',
            url: 'https://dnschecker.org/hex-to-colortone',
            favicon: '/favicons/hex-to-pantone.webp',
            tags: ['Converter', 'Color names', 'HEX', 'Pantone', 'Information'],
          },
          {
            title: 'OKLCH Color',
            url: 'https://oklch.fyi/convert',
            favicon: '/favicons/oklch-color.webp',
            tags: ['Converter', 'Guide', 'Bulk'],
          },
        ],
      },
      designSystems: {
        items: [
          {
            title: 'Component Gallery',
            url: 'https://component.gallery/design-systems',
            favicon: '/favicons/component-gallery.webp',
            tags: ['Collection', 'Companies', 'Brands', 'Links'],
          },
          {
            title: 'Design Systems Surf',
            url: 'https://designsystems.surf/design-systems',
            favicon: '/favicons/design-systems-surf.webp',
            tags: ['Collection', 'Companies', 'Brands', 'Figma', 'Storybook'],
          },
          {
            title: 'Hey Design Systems',
            url: 'https://heydesign.systems',
            favicon: '/favicons/hey-design-systems.webp',
            tags: ['Tutorial', 'Chcecklist', 'How to'],
          },
          {
            title: 'Design Decks',
            url: 'https://www.deck.gallery',
            favicon: '/favicons/design-decks.webp',
            tags: ['Documents', 'Reports', 'Brand guidelines'],
          },
          {
            title: 'Brandguide',
            url: 'https://brandguide.page',
            favicon: '/favicons/brandguide.webp',
            tags: ['Brand guidelines', 'Collection', 'Brands'],
          },
        ],
      },
      mockups: {
        items: [
          {
            title: 'Creatoom Scene Mockups',
            url: 'https://creatoom.com/product-category/scene-mockups/?products_group&max_price=0',
            favicon: '/favicons/creatoom-scene-mockups.webp',
            tags: ['Packaging', 'Studio', 'Modern', 'Photoshoot'],
          },
          {
            title: 'Wanna This',
            url: 'https://wannathis.one/mockups/free',
            favicon: '/favicons/wanna-this.webp',
            tags: ['Packaging', 'Studio', 'Modern', 'Devices', 'Screens'],
          },
          {
            title: 'Pixel Buddha Mockups',
            url: 'https://pixelbuddha.net/mockups?type=freebie',
            favicon: '/favicons/pixel-buddha-mockups.webp',
            tags: ['Packaging', 'Clothing', 'Stationery', 'Devices', 'Logo'],
          },
          {
            title: 'Designbolts',
            url: 'https://www.designbolts.com/category/mockup-psd',
            favicon: '/favicons/designbolts.webp',
            tags: ['Packaging', 'Clothing', 'Stationery', 'Devices', 'Logo'],
          },
          {
            title: 'Lapa Ninja',
            url: 'https://www.lapa.ninja/freebies/mockups',
            favicon: '/favicons/lapa-ninja.webp',
            tags: ['Devices', 'Angles', 'Apple'],
          },
          {
            title: 'LS Graphics',
            url: 'https://www.ls.graphics/free-mockups',
            favicon: '/favicons/ls-graphics.webp',
            tags: ['Studio', 'Devices', 'Packaging', 'Clothing', 'Stationery'],
          },
          {
            title: 'Mockups Design',
            url: 'https://mockups-design.com',
            favicon: '/favicons/mockups-design.webp',
            tags: ['Minimalistic', 'Devices', 'Packaging', 'Clothing', 'Stationery'],
          },
          {
            title: 'Mr Mockup',
            url: 'https://mrmockup.com/free-mockups',
            favicon: '/favicons/mr-mockup.webp',
            tags: ['Minimalistic', 'Devices', 'Packaging', 'Clothing', 'Stationery'],
          },
          {
            title: 'Unblast',
            url: 'https://unblast.com',
            favicon: '/favicons/unblast.webp',
            tags: ['Minimalistic', 'Devices', 'Packaging', 'Clothing', 'Stationery'],
          },
          {
            title: 'Good Mockups',
            url: 'https://goodmockups.com',
            favicon: '/favicons/good-mockups.webp',
            tags: ['Minimalistic', 'Devices', 'Packaging', 'Clothing', 'Stationery'],
          },
          {
            title: 'Pixeden',
            url: 'https://www.pixeden.com/free',
            favicon: '/favicons/pixeden.webp',
            tags: ['Minimalistic', 'Packaging', 'Clothing', 'Devices'],
          },
          {
            title: 'Yellow Images',
            url: 'https://yellowimages.com/mockups/category/free-mockups',
            favicon: '/favicons/yellow-images.webp',
            tags: ['Minimalistic', 'No backrground', 'Packaging', 'Devices'],
          },
          {
            title: 'Creatoom',
            url: 'https://creatoom.com/product-category/items/free-mockups',
            favicon: '/favicons/creatoom.webp',
            tags: ['Minimalistic', 'No backrground', 'Packaging', 'Devices'],
          },
          {
            title: 'Morflax Toolset',
            url: 'https://studio.morflax.com/toolset',
            favicon: '/favicons/morflax-toolset.webp',
            tags: ['Packaging', 'Shapes', 'Motion', 'Marketing', 'Clothing'],
          },
          {
            title: 'PostSpark',
            url: 'https://postspark.app/screenshot',
            favicon: '/favicons/postspark.webp',
            tags: ['Open graph', 'Generator', 'Backgrounds', 'Banner'],
          },
          {
            title: 'Shots',
            url: 'https://shots.so',
            favicon: '/favicons/shots.webp',
            tags: ['Open graph', 'Generator', 'Backgrounds', 'Multiple', 'Liquid glass'],
          },
          {
            title: 'TextLab',
            url: 'https://textlab.javii.tools/',
            favicon: '/favicons/textlab.webp',
            tags: ['Notifications', 'Messages', 'Bubbles', 'Generator', 'Comments'],
          },
          {
            title: 'Morflax Things',
            url: 'https://things.morflax.com',
            favicon: '/favicons/morflax-things.webp',
            tags: ['Devices', 'Generator', 'Apple', 'Online'],
          },
          {
            title: 'Facebook Design Device',
            url: 'https://www.meta.com/design-at-meta/tools/devices',
            favicon: '/favicons/facebook-design-device.webp',
            tags: ['Devices', 'Collection', 'Apple', 'Android', 'By brand', 'By category'],
          },
          {
            title: 'UltraMock',
            url: 'https://www.ultramock.io',
            favicon: '/favicons/ultramock.webp',
            tags: ['Devices', 'Animated', 'Editor', 'Mac', 'iPhone', 'Photoshoot'],
          },
          {
            title: 'Pixpine',
            url: 'https://pixpine.com/free-mockups',
            favicon: '/favicons/pixpine.webp',
            tags: ['Packaging', 'Devices', 'Minimalistic'],
          },
          {
            title: 'Mockup Tree',
            url: 'https://mockuptree.com',
            favicon: '/favicons/mockup-tree.webp',
            tags: ['Packaging', 'Social media', 'Modern'],
          },
          {
            title: 'MockupFree',
            url: 'https://mockupfree.co',
            favicon: '/favicons/mockupfree.webp',
            tags: ['Packaging', 'No background', 'Clothing'],
          },
        ],
      },
      images: {
        items: [
          {
            title: 'Pexels',
            tags: ['Stock photos', 'Videos', 'JPEG'],
            url: 'https://www.pexels.com',
            favicon: '/favicons/pexels.webp',
          },
          {
            title: 'Pixabay',
            tags: ['Stock photos', 'Videos', 'Illustrations', 'JPEG'],
            url: 'https://pixabay.com',
            favicon: '/favicons/pixabay.webp',
          },
          {
            title: 'Texture Labs',
            tags: ['Overlays', 'Grunge', 'Film', 'Lights', 'Paper', 'Glass'],
            url: 'https://texturelabs.org',
            favicon: '/favicons/texture-labs.webp',
          },
          {
            title: 'Ideogram Explore',
            tags: ['Images', 'Inspiration', 'AI generation', 'Community'],
            url: 'https://ideogram.ai/explore',
            favicon: '/favicons/ideogram-explore.webp',
          },
          {
            title: 'Craiyon',
            tags: ['Text to image', 'Images', 'AI generation', 'Community'],
            url: 'https://www.craiyon.com/es',
            favicon: '/favicons/craiyon.webp',
          },
          {
            title: 'StickPNG',
            tags: ['PNG', 'Stickers', 'Collection', 'HD'],
            url: 'https://www.stickpng.com/es',
            favicon: '/favicons/stickpng.webp',
          },
          {
            title: 'Artvee',
            url: 'https://artvee.com',
            favicon: '/favicons/artvee.webp',
            tags: ['Classical art', 'Paintings', 'Drawings', 'Illustrations', 'Posters', 'HD'],
          },
          {
            title: 'PNGWing',
            tags: ['PNG', 'Community', 'Collection', 'HD'],
            url: 'https://www.pngwing.com/es',
            favicon: '/favicons/pngwing.webp',
          },
          {
            title: 'WallpaperCat',
            tags: ['Wallpapers', '4K', 'HD', 'Videogames', 'AI', 'Abstract', 'Anime'],
            url: 'https://wallpapercat.com',
            favicon: '/favicons/wallpapercat.webp',
          },
          {
            title: 'StockSnap',
            tags: ['Stock photos', 'HD', 'CC0', 'Nature', 'Real life', 'People'],
            url: 'https://stocksnap.io',
            favicon: '/favicons/stocksnap.webp',
          },
          {
            title: 'Kaboompics',
            tags: ['Stock photos', 'Photography', 'Portraits', 'Photoshoots', 'Minimalistic'],
            url: 'https://kaboompics.com',
            favicon: '/favicons/kaboompics.webp',
          },
          {
            title: 'Openverse',
            tags: ['Stock photos', 'Images', 'Music', 'Sound effects', 'Creative Commons'],
            url: 'https://openverse.org',
            favicon: '/favicons/openverse.webp',
          },
          {
            title: 'Lummi',
            tags: ['Stock photos', 'AI images', 'HD', 'Illustrations', '3D'],
            url: 'https://www.lummi.ai',
            favicon: '/favicons/lummi.webp',
          },
          {
            title: 'Cosmos',
            tags: ['Paintings', 'Portraits', 'Classical art', 'Vintage'],
            url: 'https://www.cosmos.so/public-work',
            favicon: '/favicons/cosmos.webp',
          },
          {
            title: 'NoMoreCopyright AI image Generator',
            tags: ['Text to image', 'AI generation', 'Images', 'No watermark', 'HD'],
            url: 'https://nomorecopyright.com',
            favicon: '/favicons/nomorecopyright-ai-image-generator.webp',
          },
          {
            title: 'Weave Silk',
            tags: ['Drawing', 'Flowing art', 'Online'],
            url: 'http://weavesilk.com',
            favicon: '/favicons/weave-silk.webp',
          },
        ],
      },
      audio: {
        items: [
          {
            title: 'Vocal Remover',
            tags: ['Separate music', 'Change tone', 'BPM', 'AI', 'Online'],
            url: 'https://vocalremover.org/es',
            favicon: '/favicons/vocal-remover.webp',
          },
          {
            title: 'LuvVoice',
            tags: ['Text to speech', 'Voice editing', 'AI', 'Online'],
            url: 'https://luvvoice.com/es',
            favicon: '/favicons/luvvoice.webp',
          },
          {
            title: 'SpeechMa',
            tags: ['Text to speech', 'Voice editing', 'AI', 'Online'],
            url: 'https://speechma.com',
            favicon: '/favicons/speechma.webp',
          },
          {
            title: 'Freesound',
            tags: ['Sound effects', 'Music', 'SFX'],
            url: 'https://freesound.org',
            favicon: '/favicons/freesound.webp',
          },
        ],
      },
      editing: {
        items: [
          {
            title: 'Artkit Image Editor',
            tags: [
              'Tools',
              'Motion',
              'Web graphics',
              'ASCII',
              'Halftone',
              'Retro',
              'Tracking',
              'Glitch',
            ],
            url: 'https://artkit.cc',
            favicon: '/favicons/artkit-image-editor.webp',
          },
          {
            title: 'FlexClip Compress Video',
            tags: ['Online', 'Customizable', 'WebM', 'MP4', 'MOV'],
            url: 'https://www.flexclip.com/es/tools/compress-video',
            favicon: '/favicons/flexclip-compress-video.webp',
          },
          {
            title: 'Upscale Media',
            tags: ['Online', 'Upscale', 'Images', '2x', 'AI'],
            url: 'https://www.upscale.media/es',
            favicon: '/favicons/upscale-media.webp',
          },
          {
            title: 'Free Upscaler Video',
            tags: ['Browser', 'Upscale', 'Video', '2x', 'AI'],
            url: 'https://free.upscaler.video',
            favicon: '/favicons/free-upscaler-video.webp',
          },
          {
            title: 'Formia',
            url: 'https://formia.so',
            favicon: '/favicons/formia.webp',
            tags: ['Tool', 'Editor', '3D logos', 'Texture', 'Metal', 'Liquid'],
          },
          {
            title: 'Antlii',
            url: 'https://antlii.work',
            favicon: '/favicons/antlii.webp',
            tags: ['Tool', 'Editor', '3D', 'Animations', 'Effects', 'Unique'],
          },
          {
            title: 'Shaders Paper Design',
            tags: [
              'Shaders',
              'Textures',
              'Dithering',
              'Halftone',
              'Liquid metal',
              'Heatmap',
              'Mesh gradients',
              'Backgrounds',
            ],
            url: 'https://shaders.paper.design',
            favicon: '/favicons/shaders-paper-design.webp',
          },
          {
            title: 'Pixel Crash',
            tags: ['Video effect', 'Online', 'Texture', 'Mapping'],
            url: 'https://www.pixelcrash.xyz',
            favicon: '/favicons/pixel-crash.webp',
            inverted: true,
          },
          {
            title: 'Type Tools',
            url: 'https://www.type-tools.com/dither/dither.html',
            favicon: '/favicons/type-tools.webp',
            tags: ['Typography', 'Dither', 'Blur', 'Line', 'Slice'],
          },
          {
            title: 'GrainRad',
            tags: [
              'Image effects',
              'Textures',
              'Matrix',
              'ASCII',
              'Edge detection',
              'Pixel sort',
              'VHS',
              'Dots',
              'Dithering',
            ],
            url: 'https://grainrad.com',
            favicon: '/favicons/grainrad.webp',
          },
          {
            title: 'Tooooools',
            tags: [
              'Image effects',
              'Textures',
              'Stippling',
              'Distort',
              'Displace',
              'Bevel',
              'Scatter',
              'Cellular automata',
              'CRT',
            ],
            url: 'https://www.tooooools.app',
            favicon: '/favicons/tooooools.webp',
          },
          {
            title: 'PhotoRoom Background Remover',
            tags: ['Generator', 'PNG', 'HD', 'Online'],
            url: 'https://www.photoroom.com/tools/background-remover',
            favicon: '/favicons/photoroom-background-remover.webp',
          },
        ],
      },
      video: {
        items: [
          {
            title: 'Unicorn Studio',
            tags: ['Shaders', 'Online', 'Editor', 'Canvas', 'AI', 'MP4'],
            url: 'https://www.unicorn.studio',
            favicon: '/favicons/unicorn-studio.webp',
          },
          {
            title: 'Intangible AI',
            tags: ['Real world editing', '3D editing', 'Film', 'Advertising', 'Events', 'Games'],
            url: 'https://www.intangible.ai',
            favicon: '/favicons/intangible-ai.webp',
          },
          {
            title: 'DroneStock',
            tags: ['Drone shots', '4K', 'Nature', 'Cities', 'People', 'Sports'],
            url: 'https://dronestock.com',
            favicon: '/favicons/dronestock.webp',
          },
          {
            title: 'Yarn',
            tags: ['Memes', 'Clips', 'English', 'Movies', 'TV'],
            url: 'https://getyarn.io',
            favicon: '/favicons/yarn.webp',
          },
          {
            title: 'Mixkit',
            tags: ['Stock videos', 'Music', 'Sound effects', 'Video templates', '4K'],
            url: 'https://mixkit.co',
            favicon: '/favicons/mixkit.webp',
          },
          {
            title: 'Kling AI',
            tags: ['Text to video', 'AI generation', 'Video', 'HD', 'First/last frame'],
            url: 'https://kling.ai/app/video/new',
            favicon: '/favicons/kling-ai.webp',
          },
        ],
      },
    },
  },
  seo: {
    categories: {
      general: {
        items: [
          {
            title: 'SEO Studio',
            tags: ['Multi-porpuse', 'Checkers', 'Generators', 'Converters'],
            url: 'https://seostudio.tools',
            favicon: '/favicons/seo-studio.webp',
          },
          {
            title: 'SERanking Keyword suggestion',
            tags: ['Keywords', 'Ideas', 'SERP'],
            url: 'https://seranking.com/es/keyword-suggestion-tool.html',
            favicon: '/favicons/seranking-keyword-suggestion.webp',
          },
          {
            title: 'CrUX Vis',
            tags: ['UX report', 'Web performance'],
            url: 'https://cruxvis.withgoogle.com/#',
            favicon: '/favicons/crux-vis.webp',
          },
          {
            title: 'W3C Nu HTML Checker',
            tags: ['HTML', 'Validation', 'Web standards', 'Semantic check'],
            url: 'https://validator.w3.org/nu',
            favicon: '/favicons/w3c-nu-html-checker.webp',
          },
          {
            title: 'Structured Data Testing Tool',
            tags: ['JSON-LD', 'Schema Markup', 'Validation'],
            url: 'https://search.google.com/test/rich-results',
            favicon: '/favicons/structured-data-testing-tool.webp',
          },
          {
            title: 'Site SEO Analyzer',
            tags: ['Content quality', 'Indexability', 'Security', 'Performance'],
            url: 'https://www.siteseoanalyzer.me',
            favicon: '/favicons/site-seo-analyzer.webp',
          },
          {
            title: 'TitleTag Preview',
            tags: ['Metadata', 'Title tag', 'Description'],
            url: 'https://titletagpreview.com',
            favicon: '/favicons/titletag-preview.webp',
          },
          {
            title: 'Web-check',
            tags: ['DNS checker', 'Cookies', 'Hosting servers', 'Headers', 'SSL', 'Whois'],
            url: 'https://web-check.xyz/check',
            favicon: '/favicons/web-check.webp',
          },
          {
            title: 'Domain Digger',
            tags: ['DNS', 'Records', 'SSL', 'Whois', 'Lookup'],
            url: 'https://digger.tools',
            favicon: '/favicons/domain-digger.webp',
          },
          {
            title: 'CleanMySeo',
            tags: ['Meta tags', 'Open Graph'],
            url: 'https://www.cleanmyseo.com',
            favicon: '/favicons/cleanmyseo.webp',
          },
          {
            title: 'SERanking Title and Description Checker',
            tags: ['Google', 'Preview', 'Metadata'],
            url: 'https://seranking.com/free-tools/title-description-checker.html',
            favicon: '/favicons/seranking-title-and-description-checker.webp',
          },
          {
            title: 'CSS Code Quality',
            tags: ['Maintainability', 'Performance', 'Complexity', 'CSSLint'],
            url: 'https://www.projectwallace.com/css-code-quality',
            favicon: '/favicons/css-code-quality.webp',
          },
          {
            title: 'Seobility',
            tags: ['In-depth', 'Tecnical', 'On-page', 'Analysis'],
            url: 'https://www.seobility.net/es/seochecker',
            favicon: '/favicons/seobility.webp',
          },
          {
            title: 'Security Headers',
            tags: ['Analysis', 'HTTP', 'Warnings', 'Recommendation'],
            url: 'https://securityheaders.com',
            favicon: '/favicons/security-headers.webp',
          },
          {
            title: 'Accessibility Checker',
            tags: [' WCAG', 'ADA', 'Best practices'],
            url: 'https://www.accessibilitychecker.org',
            favicon: '/favicons/accessibility-checker.webp',
          },
          {
            title: 'SSL Labs',
            tags: ['SSL', 'Security', 'Analysis'],
            url: 'https://www.ssllabs.com/ssltest',
            favicon: '/favicons/ssl-labs.webp',
          },
          {
            title: 'Can I include',
            tags: ['HTML', 'Child tags', 'Parent tags', 'MDN', 'Best practices'],
            url: 'https://caninclude.onrender.com',
            favicon: '/favicons/can-i-include.webp',
          },
        ],
      },
    },
  },
  services: {
    categories: {
      general: {
        items: [
          {
            title: 'Can I run AI',
            url: 'https://www.canirun.ai',
            favicon: '/favicons/can-i-run-ai.webp',
            tags: ['Local models', 'Requirements', 'Stats', 'Playground'],
          },
          {
            title: 'FreeBuff AI',
            url: 'https://freebuff.com/',
            favicon: '/favicons/freebuff-ai.webp',
            tags: ['Vibe coding', 'Agents', 'Web', 'Desktop', 'CLI'],
          },
          {
            title: 'EnvManager',
            url: 'https://envmanager.com/share',
            favicon: '/favicons/envmanager.webp',
            tags: ['Environment variables', 'Share', 'Security'],
          },
          {
            title: 'Recordly',
            tags: ['Screen recording', 'Desktop', 'Windows', 'Mac', 'Open source'],
            url: 'https://recordly.dev',
            favicon: '/favicons/recordly.webp',
          },
          {
            title: 'VoiceBox',
            tags: ['Clone voice', 'Open source', 'Speech', 'Audio'],
            url: 'https://github.com/jamiepine/voicebox',
            favicon: '/favicons/voicebox.webp',
          },
          {
            title: 'ComeCut',
            tags: ['CapCut alternative', 'MP4', 'web', 'desktop'],
            url: 'https://github.com/juntaosun/ComeCut',
            favicon: '/favicons/comecut.webp',
          },
          {
            title: 'Agent QA',
            url: 'https://vostride.com/',
            favicon: '/favicons/agent-qa.webp',
            tags: ['Testing', 'Web', 'Mobile', 'CLI', 'AI'],
          },
          {
            title: 'Koboyo',
            tags: ['Canvas', 'Sketches', 'Diagrams', 'Notes'],
            url: 'https://koboyo.com',
            favicon: '/favicons/koboyo.webp',
          },
          {
            title: 'Diagrams',
            tags: ['Whiteboard', 'Flowcharts', 'Mind maps', 'Web'],
            url: 'https://app.diagrams.net/',
            favicon: '/favicons/diagrams.webp',
          },
          {
            title: 'Media Bunny',
            tags: ['Converter', 'Media operations', ' FFmpeg for web'],
            url: 'https://mediabunny.dev',
            favicon: '/favicons/media-bunny.webp',
          },
          {
            title: 'Onelang IDE',
            tags: ['Translate code', 'TypeScript', 'C++', 'C#', 'PHP', 'Python', 'Swift'],
            url: 'https://ide.onelang.io',
            favicon: '/favicons/onelang-ide.webp',
          },
          {
            title: 'CRT Name',
            tags: ['Subdomains', 'Index', 'DNS', 'Domains'],
            url: 'https://crt.name/',
            favicon: '/favicons/crt-name.webp',
          },
          {
            title: 'Playphrase',
            tags: ['Search phrases', 'Movies', 'Clips', 'TV'],
            url: 'https://www.playphrase.me',
            favicon: '/favicons/playphrase.webp',
          },
          {
            title: 'IPQuery',
            tags: ['IP info', 'Geolocation', 'HTTP', 'API'],
            url: 'https://ipquery.io',
            favicon: '/favicons/ipquery.webp',
          },
          {
            title: 'IP Guide',
            tags: ['IP info', 'Geolocation', 'HTTP', 'API'],
            url: 'https://ip.guide',
            favicon: '/favicons/ip-guide.webp',
          },
          {
            title: 'Porkbun',
            tags: ['Domain registrar', 'Domains', 'SSL', 'Email forwarding', 'DNS'],
            url: 'https://porkbun.com',
            favicon: '/favicons/porkbun.webp',
          },
          {
            title: 'Gmail Postmaster',
            tags: ['Email delivery', 'Reputation', 'Validate sender'],
            url: 'https://gmail.com/postmaster',
            favicon: '/favicons/gmail-postmaster.webp',
          },
          {
            title: 'Goatcounter',
            tags: ['Analytics', 'Open source', 'Privacy friendly'],
            url: 'https://www.goatcounter.com',
            favicon: '/favicons/goatcounter.webp',
          },
          {
            title: 'Ahrefs Web Analytics',
            tags: ['Analytics', 'Marketing', 'Cookie-free', 'GDPR'],
            url: 'https://ahrefs.com/web-analytics',
            favicon: '/favicons/ahrefs-web-analytics.webp',
          },
          {
            title: 'Yaak',
            tags: ['API testing', 'HTTP', 'local-first'],
            url: 'https://yaak.app',
            favicon: '/favicons/yaak.webp',
          },
          {
            title: 'TopoExport',
            tags: ['Topography', 'Export', 'Maps', 'CAD', '2D', '3D'],
            url: 'https://topoexport.com',
            favicon: '/favicons/topoexport.webp',
          },
          {
            title: 'SunEarth Tools',
            tags: ['Tools', 'Sun position', 'CO2', 'Photovoltaic'],
            url: 'https://www.sunearthtools.com/index.php',
            favicon: '/favicons/sunearth-tools.webp',
          },
          {
            title: 'Regex Vis',
            tags: ['Visual', 'Diagrams', 'Explanation'],
            url: 'https://regex-vis.com',
            favicon: '/favicons/regex-vis.webp',
          },
          {
            title: 'SVG Viewer',
            tags: ['Editor', 'Inspector', 'Optimizer'],
            url: 'https://www.svgviewer.dev',
            favicon: '/favicons/svg-viewer.webp',
          },
          {
            title: 'Meshy AI',
            tags: ['3D models', 'Image to 3D', 'Text to 3D', 'Online'],
            url: 'https://www.meshy.ai',
            favicon: '/favicons/meshy-ai.webp',
          },
          {
            title: 'Vertex42',
            url: 'https://www.vertex42.com/',
            favicon: '/favicons/vertex42.webp',
            tags: ['Templates', 'Spreadsheets', 'Productivity', 'Excel'],
          },
          {
            title: 'Planilla Excel',
            url: 'https://www.planillaexcel.com/plantillas',
            favicon: '/favicons/planilla-excel.webp',
            tags: ['Templates', 'Spreadsheets', 'Productivity', 'Excel'],
          },
        ],
      },
    },
  },
  learning: {
    categories: {
      general: {
        items: [
          {
            title: 'LibreríasJS',

            tags: [
              'Tutorials',
              'Spanish',
              'JS',
              'frontend',
              'react',
              'angular',
              'vue',
              'node',
              'español',
            ],
            url: 'https://libreriasjs.com',
            favicon: '/favicons/librerasjs.webp',
          },
          {
            title: 'DevChallenges',

            tags: [
              'Real life projects',
              'JS',
              'frontend',
              'react',
              'angular',
              'vue',
              'node',
              'español',
            ],
            url: 'https://devchallenges.io',
            favicon: '/favicons/devchallenges.webp',
          },
          {
            title: 'CoDrops',
            tags: ['Tutorials', ' Libraries', 'Motion', 'Animated', 'Modern'],

            url: 'https://tympanus.net/codrops/category/tutorials',
            favicon: '/favicons/codrops.webp',
          },
          {
            title: 'Gutenberg',
            url: 'https://www.gutenberg.org',
            favicon: '/favicons/gutenberg.webp',
            tags: ['eBooks', 'Collection', 'Online'],
          },
          {
            title: 'Coddy.tech',
            url: 'https://coddy.tech',
            favicon: '/favicons/coddytech.webp',
            tags: ['Programming', 'Spanish', 'Interactive', 'All languages'],
          },
          {
            title: 'Goalkicker',
            url: 'https://books.goalkicker.com',
            favicon: '/favicons/goalkicker.webp',
            tags: ['Programming', 'PDF', 'Books', 'Cheat sheets', 'eBooks'],
          },
          {
            title: 'Design for Engineers',
            url: 'https://didoesdigital.com/project/design-for-engineers/',
            favicon: '/favicons/design-for-engineers.webp',
            tags: ['Foundation', 'Guide', 'Web design', 'UX', 'UI'],
          },
          {
            title: 'Code for Designers',
            url: 'https://didoesdigital.com/project/code-for-designers/',
            favicon: '/favicons/code-for-designers.webp',
            tags: ['Foundation', 'Guide', 'Web design', 'UX', 'UI'],
          },
          {
            title: 'Web Interface Guidelines',
            url: 'https://interfaces.rauno.me/',
            favicon: '/favicons/web-interface-guidelines.webp',
            tags: ['Accessibility', 'UI', 'UX', 'Design', 'Foundation'],
          },
          {
            title: 'Exercism',
            url: 'https://exercism.org',
            favicon: '/favicons/exercism.webp',
            tags: ['Programming', 'Practice', 'All languages', 'Mentorship'],
          },
          {
            title: 'QuickRef.me',
            url: 'https://quickref.me',
            favicon: '/favicons/quickrefme.webp',
            tags: ['Programming', 'Reference', 'All languages', 'Cheat sheets'],
          },
          {
            title: 'A11y Collective',
            url: 'https://www.a11y-collective.com/blog',
            favicon: '/favicons/a11y-collective.webp',
            tags: ['Accessibility', 'WCAG', 'Guide', 'Fundamentals'],
          },
          {
            title: 'Google SEO Starter Guide',
            url: 'https://developers.google.com/search/docs/fundamentals/seo-starter-guide',
            favicon: '/favicons/google-seo-starter-guide.webp',
            tags: ['SEO', 'Google', 'Guide', 'Fundamentals'],
          },
          {
            title: 'Learn Performance',
            url: 'https://web.dev/learn/performance',
            favicon: '/favicons/learn-performance.webp',
            tags: ['Performance', 'Google', 'Guide', 'Fundamentals'],
          },
          {
            title: 'The Copenhagen Book',
            url: 'https://thecopenhagenbook.com',
            favicon: '/favicons/the-copenhagen-book.webp',
            tags: ['Authentication', 'Security', 'Fundamentals'],
          },
          {
            title: 'Grow',
            url: 'https://grow.google/intl',
            favicon: '/favicons/grow.webp',
            tags: ['Business', 'Google', 'Marketing', 'Courses'],
          },
          {
            title: 'Regexr',
            url: 'https://regexr.com',
            favicon: '/favicons/regexr.webp',
            tags: ['Regex', 'Reference', 'Guide', 'Fundamentals'],
          },
          {
            title: 'Dofactory SQL',
            url: 'https://www.dofactory.com/sql/editor',
            favicon: '/favicons/dofactory-sql.webp',
            tags: ['Editor', 'Online', 'Practice', 'Guide'],
          },
          {
            title: 'Shell Howto',
            url: 'https://www.shell.how',
            favicon: '/favicons/shell-howto.webp',
            tags: ['CLI', 'Commands', 'Practice', 'Guide'],
          },
          {
            title: 'Patterns',
            url: 'https://www.patterns.dev',
            favicon: '/favicons/patterns.webp',
            tags: ['Design', 'Patterns', 'JavaScript', 'Guide'],
          },
          {
            title: 'UX Challenges',
            url: 'https://www.uxtools.co/challenges',
            favicon: '/favicons/ux-challenges.webp',
            tags: ['UX', 'Practice', 'Fundamentals'],
          },
          {
            title: 'Laws of UX',
            url: 'https://lawsofux.com',
            favicon: '/favicons/laws-of-ux.webp',
            tags: ['UX', 'Reference', 'Guide', 'Fundamentals'],
          },
          {
            title: 'Name That UI',
            url: 'https://namethatui.com/',
            favicon: '/favicons/name-that-ui.webp',
            tags: ['UI', 'Design', 'Components', 'Patterns', 'Styles'],
          },
          {
            title: 'Hacksplaining',
            url: 'https://www.hacksplaining.com/lessons',
            favicon: '/favicons/hacksplaining.webp',
            tags: ['Security', 'OWASP', 'Fundamentals', 'Guide'],
          },
          {
            title: 'Frontify Brand Guidelines',
            url: 'https://www.frontify.com/en/guide/brand-guidelines',
            favicon: '/favicons/frontify-brand-guidelines.webp',
            tags: ['How to', 'Branding', 'Guide', 'Steps'],
          },
          {
            title: '12 Principles of Animation',
            url: 'https://www.raphaelsalaja.com/library/12-principles-of-animation',
            favicon: '/favicons/12-principles-of-animation.webp',
            tags: ['How to', 'Motion', 'Guide', 'Interactive', 'Visual'],
          },
        ],
      },
    },
  },
} as const

import type { BadgeProps } from '@/components/badge'

export const FEATURE_TAGS: Record<string, BadgeProps['variant']> = {
  marketing: 'green',
  learning: 'cyan',
  development: 'indigo',
  cli: 'slate',
  devices: 'slate',
  tools: 'lime',
  branding: 'red',
  minimalistic: 'white',
  monochrome: 'white',
  clean: 'white',
  ux: 'cyan',
  motion: 'pink',
  interactive: 'pink',
  'micro-interactions': 'pink',
  unique: 'yellow',
  online: 'blue',
  seo: 'green',
  ui: 'blue',
  mockups: 'violet',
  animated: 'teal',
  ai: 'pink',
  icons: 'yellow',
  backgrounds: 'slate',
  'landing page': 'sky',
  modern: 'indigo',
  '3d': 'purple',
  '2d': 'purple',
  sounds: 'orange',
  music: 'orange',
  http: 'lime',
  editor: 'emerald',
  generator: 'lime',
  converter: 'red',
  logos: 'sky',
  community: 'blue',
  practice: 'indigo',
  dashboard: 'orange',
  'how to': 'violet',
} as const

export const RECOMMENDED_TAGS = [
  'Branding',
  'Minimalistic',
  'SEO',
  'UI',
  'Mockups',
  'Security',
  'Animated',
  'AI',
  'Icons',
  'Backgrounds',
  'Landing page',
  'Modern',
  '3D',
  'Sounds',
  'Editor',
  'Community',
] as const
